language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend.

 # Tag images
  - docker tag reverseproxy prubayita/reverseproxy:v1
  - docker tag udagram-api-feed prubayita/udagram-api-feed:v1
  - docker tag udagram-api-user prubayita/udagram-api-user:v1
  - docker tag udagram-frontend prubayita/udagram-frontend:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push prubayita/reverseproxy:v1
  - docker push prubayita/udagram-api-feed:v1
  - docker push prubayita/udagram-api-user:v1
  - docker push prubayita/udagram-frontend:v1